version: '3.4'

services:
  api:
    build: .
    volumes:
      - .:/project
    ports:
      - 3002:3002
    working_dir: "/project"
    command: bash -c "npm install && npm rebuild && npm run migrations && npm start"
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
    links:
      - db
  db:
    image: postgres:10.11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=2000'

volumes:
  pgdata:
