# This workflow will run tests using node and then publish a package to AWS when a release is created

name: Publish to AWS

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm run lint
      - run: npm test

  publish-aws:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: npm install dependencies
        run: npm install
        
      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
